<?php

namespace App\Tests\ExtensionTrait;

use iikoExchangeBundle\Contract\Extensions\WithMappingExtensionInterface;
use iikoExchangeBundle\Contract\Mapping\MappingInterface;
use iikoExchangeBundle\ExtensionTrait\WithMappingExtensionTrait;
use PHPUnit\Framework\TestCase;

class WithMappingExtensionTraitTest extends TestCase
{
	protected WithMappingExtensionInterface $instance;

	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->instance = new TestClassMapping();
	}

	public function testSetMappingValues()
	{

	}

	public function testAddMapping()
	{

	}

	public function testGetMapping()
	{
		$this->instance->setMappingValues('__TEST__',
			[
				[
					MappingInterface::FIELD_IDENTIFIERS => [
						"NAME" => "Bob",
						"SURNAME" => "DILLAN"
					],
					MappingInterface::FIELD_VALUES => [
						"VALUE" => "OUR SINGER IS %NAME% %SURNAME%"
					]
				]
			]);

		$this->assertEquals("OUR SINGER IS Bob DILLAN", $this->instance->getMappingValue("__TEST__", [
			"NAME" => "Bob",
			"SURNAME" => "DILLAN"
		], "VALUE"));
	}

	public function testGetUniqMappingIdentifiers()
	{

	}

	public function testGetMappingValues()
	{

	}
}

class TestClassMapping implements WithMappingExtensionInterface
{
	use WithMappingExtensionTrait;
}
